apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: bianjie-demo
  name: bianjie-demo
  namespace: bianjie
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: bianjie-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: bianjie-demo
    spec:
      containers:
      - image: repository.bianjie.ai/bianjie/demo:2021072701
        imagePullPolicy: Always
        name: app
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: nexus-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: bianjie-demo
  namespace: bianjie
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: bianjie-demo
  sessionAffinity: None
  type: ClusterIP

